<a href="https://colab.research.google.com/github/sistlasriram/ssr-credit-card-fraud-detection/blob/main/ssr_Credit_card_fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
140698,83876,1.297031,0.260234,-0.165836,0.304460,0.238056,-0.084983,-0.056115,0.029952,-0.115999,...,-0.315545,-0.948937,-0.024322,-0.883643,0.335230,0.150161,-0.029612,0.008220,0.99,0.0
140699,83876,1.200272,0.259410,0.397862,0.631576,-0.476806,-0.882324,-0.062362,-0.028223,-0.130967,...,-0.231443,-0.739076,0.151545,0.475489,0.134602,0.066882,-0.031207,0.020989,0.89,0.0
140700,83877,-0.939078,1.234767,1.433774,-0.097576,-0.255769,-0.689204,0.509961,0.153369,0.179511,...,-0.257956,-0.582912,0.080816,0.334513,-0.257496,0.094942,0.487942,0.239537,4.49,0.0
140701,83879,1.170286,0.563313,-0.271928,1.394477,-0.038260,-1.000654,0.126524,-0.031662,0.139095,...,-0.038141,-0.086158,-0.033513,0.220516,0.517620,-0.312217,0.041102,0.053760,1.00,0.0
140702,83879,-1.376888,0.304186,2.232899,-0.740000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140703 entries, 0 to 140702
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    140703 non-null  int64
 1   V1      140703 non-null  float64
 2   V2      140703 non-null  float64
 3   V3      140703 non-null  float64
 4   V4      140703 non-null  float64
 5   V5      140702 non-null  float64
 6   V6      140702 non-null  float64
 7   V7      140702 non-null  float64
 8   V8      140702 non-null  float64
 9   V9      140702 non-null  float64
 10  V10     140702 non-null  float64
 11  V11     140702 non-null  float64
 12  V12     140702 non-null  float64
 13  V13     140702 non-null  float64
 14  V14     140702 non-null  float64
 15  V15     140702 non-null  float64
 16  V16     140702 non-null  float64
 17  V17     140702 non-null  float64
 18  V18     140702 non-null  float64
 19  V19     140702 non-null  float64
 20  V20     140702 non-null  float64
 21  V21     140702 non-null  float64
 22  V22     140702 non-null  float64
 23  V23     140702 non-null  float64
 24  V24     140702 non-null  float64
 25  V25     140702 non-null  float64
 26  V26     140702 non-null  float64
 27  V27     140702 non-null  float64
 28  V28     140702 non-null  float64
 29  Amount  140702 non-null  float64
 30  Class   140702 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 33.3 MB

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
credit_card_data['Class'].value_counts()

Class
0.0    140438
1.0       264
Name: count, dtype: int64

In [ ]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(140438, 31)
(264, 31)

In [ ]:
legit.Amount.describe()

count    140438.000000
mean         91.068217
std         247.065709
min           0.000000
25%           6.000000
50%          23.900000
75%          80.760000
max       19656.530000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     264.000000
mean      115.387008
std       245.189867
min         0.000000
25%         1.000000
50%         9.560000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,52034.876842,-0.239504,0.011245,0.687392,0.131415,-0.275448,0.082153,-0.106135,0.062394,-0.088075,...,0.042180,-0.041927,-0.118336,-0.033151,0.012195,0.130022,0.023506,-0.000321,0.002165,91.068217
1.0,42420.212121,-5.610819,3.946507,-7.143814,4.512206,-3.977333,-1.480669,-5.936405,1.508791,-2.604923,...,0.239899,1.256981,-0.311690,-0.116543,-0.107463,0.197988,0.056528,0.489643,0.081783,115.387008

In [ ]:
legit_sample = legit.sample(n=492)

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
132808,80120,-1.360026,0.606477,1.364320,0.637913,0.380046,-0.338462,-0.221189,0.661689,-1.191629,...,-0.048508,-0.540477,-0.092920,-0.011851,-0.095410,0.283195,-0.056223,-0.095508,1.29,0.0
3242,2801,-0.634162,0.902132,1.120934,-2.166582,0.150908,-1.293422,1.118935,-0.341945,0.632108,...,0.105464,0.746335,-0.280673,0.558309,0.093367,-0.867672,0.345233,0.039934,1.00,0.0
55144,46806,1.373832,-0.431172,0.463694,-0.588681,-1.097206,-1.050555,-0.398657,-0.240967,-0.907471,...,-0.637659,-1.412615,0.236614,0.378824,-0.038092,0.736190,-0.055143,0.016170,15.98,0.0
49094,43908,-0.704389,0.409997,1.930241,-0.968743,-0.507781,-0.519703,0.424969,-0.398085,1.379027,...,0.192346,1.006087,-0.402990,0.476502,0.121020,-0.528203,-0.350093,-0.052032,30.39,0.0
32326,36747,-1.330466,0.987610,1.359774,-0.000422,0.377443,-0.727478,0.523374,0.352770,-0.821368,...,0.053785,-0.185286,-0.310823,-0.131065,0.659685,-0.495506,-0.083802,-0.054369,24.00,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
125342,77627,-7.139060,2.773082,-6.757845,4.446456,-5.464428,-1.713401,-6.485365,3.409395,-3.053493,...,1.303250,-0.016118,-0.876670,0.382230,-1.054624,-0.614606,-0.766848,0.409424,106.90,1.0
128479,78725,-4.312479,1.886476,-2.338634,-0.475243,-1.185444,-2.112079,-2.122793,0.272565,0.290273,...,0.550541,-0.067870,-1.114692,0.269069,-0.020572,-0.963489,-0.918888,0.001454,60.00,1.0
131272,79540,-0.114361,1.036129,1.984405,3.128243,-0.740344,1.548619,-1.701284,-2.203842,-1.242265,...,-1.032935,1.196428,-0.112857,0.254719,0.696668,0.482370,0.129969,0.223924,0.20,1.0
135718,81372,-0.885254,1.790649,-0.945149,3.853433,-1.543510,0.188582,-2.988383,1.344059,-2.294535,...,0.746160,0.550802,-0.034882,-0.567608,-0.528318,0.258782,0.506893,0.176736,7.57,1.0
137705,82289,-1.464897,1.975528,-1.077145,2.819191,0.069850,-0.789044,-1.196101,0.673654,-1.363724,...,0.174099,-0.272505,-0.031549,-0.406166,0.157769,-0.104393,0.073796,-0.041570,1.00,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0    264
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,51868.182927,-0.203042,-0.021297,0.643249,0.200586,-0.415444,0.122695,-0.092735,0.010762,-0.047175,...,0.028443,-0.044426,-0.111119,-0.111579,0.019411,0.128732,-0.024162,-0.023397,0.006263,107.132154
1.0,42420.212121,-5.610819,3.946507,-7.143814,4.512206,-3.977333,-1.480669,-5.936405,1.508791,-2.604923,...,0.239899,1.256981,-0.311690,-0.116543,-0.107463,0.197988,0.056528,0.489643,0.081783,115.387008

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

         Time        V1        V2        V3        V4        V5        V6  \
132808  80120 -1.360026  0.606477  1.364320  0.637913  0.380046 -0.338462
3242     2801 -0.634162  0.902132  1.120934 -2.166582  0.150908 -1.293422
55144   46806  1.373832 -0.431172  0.463694 -0.588681 -1.097206 -1.050555
49094   43908 -0.704389  0.409997  1.930241 -0.968743 -0.507781 -0.519703
32326   36747 -1.330466  0.987610  1.359774 -0.000422  0.377443 -0.727478
...       ...       ...       ...       ...       ...       ...       ...
125342  77627 -7.139060  2.773082 -6.757845  4.446456 -5.464428 -1.713401
128479  78725 -4.312479  1.886476 -2.338634 -0.475243 -1.185444 -2.112079
131272  79540 -0.114361  1.036129  1.984405  3.128243 -0.740344  1.548619
135718  81372 -0.885254  1.790649 -0.945149  3.853433 -1.543510  0.188582
137705  82289 -1.464897  1.975528 -1.077145  2.819191  0.069850 -0.789044

              V7        V8        V9  ...       V20       V21       V22  \
132808 -0.221189  0.661689 -1.191629  ...  0.196147 -0.048508 -0.540477
3242    1.118935 -0.341945  0.632108  ...  0.214770  0.105464  0.746335
55144  -0.398657 -0.240967 -0.907471  ... -0.441325 -0.637659 -1.412615
49094   0.424969 -0.398085  1.379027  ...  0.058164  0.192346  1.006087
32326   0.523374  0.352770 -0.821368  ... -0.049088  0.053785 -0.185286
...          ...       ...       ...  ...       ...       ...       ...
125342 -6.485365  3.409395 -3.053493  ... -0.616949  1.303250 -0.016118
128479 -2.122793  0.272565  0.290273  ... -0.718706  0.550541 -0.067870
131272 -1.701284 -2.203842 -1.242265  ...  0.732852 -1.032935  1.196428
135718 -2.988383  1.344059 -2.294535  ...  0.370041  0.746160  0.550802
137705 -1.196101  0.673654 -1.363724  ...  0.048969  0.174099 -0.272505

             V23       V24       V25       V26       V27       V28  Amount
132808 -0.092920 -0.011851 -0.095410  0.283195 -0.056223 -0.095508    1.29
3242   -0.280673  0.558309  0.093367 -0.867672  0.345233  0.039934    1.00
55144   0.236614  0.378824 -0.038092  0.736190 -0.055143  0.016170   15.98
49094  -0.402990  0.476502  0.121020 -0.528203 -0.350093 -0.052032   30.39
32326  -0.310823 -0.131065  0.659685 -0.495506 -0.083802 -0.054369   24.00
...          ...       ...       ...       ...       ...       ...     ...
125342 -0.876670  0.382230 -1.054624 -0.614606 -0.766848  0.409424  106.90
128479 -1.114692  0.269069 -0.020572 -0.963489 -0.918888  0.001454   60.00
131272 -0.112857  0.254719  0.696668  0.482370  0.129969  0.223924    0.20
135718 -0.034882 -0.567608 -0.528318  0.258782  0.506893  0.176736    7.57
137705 -0.031549 -0.406166  0.157769 -0.104393  0.073796 -0.041570    1.00

[756 rows x 30 columns]

In [ ]:
print(Y)

132808    0.0
3242      0.0
55144     0.0
49094     0.0
32326     0.0
         ...
125342    1.0
128479    1.0
131272    1.0
135718    1.0
137705    1.0
Name: Class, Length: 756, dtype: float64

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(756, 30) (604, 30) (152, 30)

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9470198675496688

In [ ]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9539473684210527